//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace T9Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/loadDictionary", ReplyAction="http://tempuri.org/IService1/loadDictionaryResponse")]
        System.IAsyncResult BeginloadDictionary(System.AsyncCallback callback, object asyncState);
        
        void EndloadDictionary(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/getPredictiveText", ReplyAction="http://tempuri.org/IService1/getPredictiveTextResponse")]
        System.IAsyncResult BegingetPredictiveText(string keyPresses, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndgetPredictiveText(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : T9Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getPredictiveTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getPredictiveTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<T9Client.ServiceReference1.IService1>, T9Client.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginloadDictionaryDelegate;
        
        private EndOperationDelegate onEndloadDictionaryDelegate;
        
        private System.Threading.SendOrPostCallback onloadDictionaryCompletedDelegate;
        
        private BeginOperationDelegate onBegingetPredictiveTextDelegate;
        
        private EndOperationDelegate onEndgetPredictiveTextDelegate;
        
        private System.Threading.SendOrPostCallback ongetPredictiveTextCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> loadDictionaryCompleted;
        
        public event System.EventHandler<getPredictiveTextCompletedEventArgs> getPredictiveTextCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult T9Client.ServiceReference1.IService1.BeginloadDictionary(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginloadDictionary(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void T9Client.ServiceReference1.IService1.EndloadDictionary(System.IAsyncResult result) {
            base.Channel.EndloadDictionary(result);
        }
        
        private System.IAsyncResult OnBeginloadDictionary(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((T9Client.ServiceReference1.IService1)(this)).BeginloadDictionary(callback, asyncState);
        }
        
        private object[] OnEndloadDictionary(System.IAsyncResult result) {
            ((T9Client.ServiceReference1.IService1)(this)).EndloadDictionary(result);
            return null;
        }
        
        private void OnloadDictionaryCompleted(object state) {
            if ((this.loadDictionaryCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.loadDictionaryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void loadDictionaryAsync() {
            this.loadDictionaryAsync(null);
        }
        
        public void loadDictionaryAsync(object userState) {
            if ((this.onBeginloadDictionaryDelegate == null)) {
                this.onBeginloadDictionaryDelegate = new BeginOperationDelegate(this.OnBeginloadDictionary);
            }
            if ((this.onEndloadDictionaryDelegate == null)) {
                this.onEndloadDictionaryDelegate = new EndOperationDelegate(this.OnEndloadDictionary);
            }
            if ((this.onloadDictionaryCompletedDelegate == null)) {
                this.onloadDictionaryCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnloadDictionaryCompleted);
            }
            base.InvokeAsync(this.onBeginloadDictionaryDelegate, null, this.onEndloadDictionaryDelegate, this.onloadDictionaryCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult T9Client.ServiceReference1.IService1.BegingetPredictiveText(string keyPresses, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetPredictiveText(keyPresses, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> T9Client.ServiceReference1.IService1.EndgetPredictiveText(System.IAsyncResult result) {
            return base.Channel.EndgetPredictiveText(result);
        }
        
        private System.IAsyncResult OnBegingetPredictiveText(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string keyPresses = ((string)(inValues[0]));
            return ((T9Client.ServiceReference1.IService1)(this)).BegingetPredictiveText(keyPresses, callback, asyncState);
        }
        
        private object[] OnEndgetPredictiveText(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((T9Client.ServiceReference1.IService1)(this)).EndgetPredictiveText(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetPredictiveTextCompleted(object state) {
            if ((this.getPredictiveTextCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getPredictiveTextCompleted(this, new getPredictiveTextCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getPredictiveTextAsync(string keyPresses) {
            this.getPredictiveTextAsync(keyPresses, null);
        }
        
        public void getPredictiveTextAsync(string keyPresses, object userState) {
            if ((this.onBegingetPredictiveTextDelegate == null)) {
                this.onBegingetPredictiveTextDelegate = new BeginOperationDelegate(this.OnBegingetPredictiveText);
            }
            if ((this.onEndgetPredictiveTextDelegate == null)) {
                this.onEndgetPredictiveTextDelegate = new EndOperationDelegate(this.OnEndgetPredictiveText);
            }
            if ((this.ongetPredictiveTextCompletedDelegate == null)) {
                this.ongetPredictiveTextCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetPredictiveTextCompleted);
            }
            base.InvokeAsync(this.onBegingetPredictiveTextDelegate, new object[] {
                        keyPresses}, this.onEndgetPredictiveTextDelegate, this.ongetPredictiveTextCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override T9Client.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<T9Client.ServiceReference1.IService1>, T9Client.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<T9Client.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginloadDictionary(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("loadDictionary", _args, callback, asyncState);
                return _result;
            }
            
            public void EndloadDictionary(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("loadDictionary", _args, result);
            }
            
            public System.IAsyncResult BegingetPredictiveText(string keyPresses, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = keyPresses;
                System.IAsyncResult _result = base.BeginInvoke("getPredictiveText", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndgetPredictiveText(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("getPredictiveText", _args, result)));
                return _result;
            }
        }
    }
}
